Adding TikhonovSVD and TSVD example networks
SCIInstitute/FwdInvToolkit pull request #57
Opened 2017-08-23 03:51 UTC by jcollfont

Added new example networks for TikhonovSVD and TSVD for completeness

2017-08-23 16:23 UTC, jessdtate commented
I'll merge this after we merge the tikhonov code into scirun.

2017-08-23 16:26 UTC, jessdtate commented
can you change the test_toolkit_file.py to reflect the new number of networks (line 68)? It's a hard coded check that we need to improve.  You will also need to rebuild the toolkit file using the bundle_toolkit code in the SCIRun/bin/SCIRun directory.

2017-08-23 17:27 UTC, jcollfont commented
Updated the number of networks in test_toolkit_file.py. 

The bundle_toolkit includes the toolkit in the SCIRun UI, right? I hadn’t done this before.

You are right, all the new networks (including isotropy method) should be applied after the merge in SCIRun with the new Tikhonov modules

2017-08-23 23:45 UTC, jessdtate commented
the bundle_toolkit script will make the toolkit to include in the SCIRun UI, yes.  It's an extra step, but it is at least scripted.  Just run 
`{path to scirun bin scirun}/bundle_toolkit Networks/FwdInvToolkit.toolkit  Networks`

2017-08-24 14:39 UTC, jcollfont commented
got it! It worked :)

2017-09-14 18:05 UTC, dcwhite requested changes

2017-09-14 18:05 UTC, dcwhite commented on test_toolkit_file.py
> +    assert len(network_xml) == 15 # update when version changes
This is not where you update number of networks. It's below...

2017-09-14 18:05 UTC, dcwhite commented on test_toolkit_file.py
> +    assert networks[0].text == '14'
...here. Please pay attention to the comments.

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.7\textwidth]{ECGToolkitGuide_figures/TikhonovSVD_module.png}
was this file added to the repo?

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.9\textwidth]{ECGToolkitGuide_figures/TikhonovSVDNetwork.png}
This seems to be missing too

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.7\textwidth]{ECGToolkitGuide_figures/TSVD_module.png}
and this one

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.9\textwidth]{ECGToolkitGuide_figures/TSVDNetwork.png}
and this

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.9\textwidth]{ECGToolkitGuide_figures/IsotropyMethod_networkExample.png}
this too

2017-09-15 19:45 UTC, jessdtate commented on Documentation/ECGTool_inverse.tex
> +        \includegraphics[width=0.9\textwidth]{ECGToolkitGuide_figures/activationBasedNetwork.png}
this one

2017-09-15 19:46 UTC, jessdtate commented
The images referenced are missing from the repo

2017-09-17 01:54 UTC, merged